version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: filenest_backend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
      - ./backend/static:/app/backend/static
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --workers 2

  nginx:
    image: nginx:stable-alpine
    container_name: filenest_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./storage:/app/storage:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/static:/app/backend/static:ro
    depends_on:
      backend:
        condition: service_healthy
