version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: filenest_backend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
      - ./data:/app/data
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 5s
      retries: 3
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --workers 2

  nginx:
    build:
      context: ./nginx
    container_name: filenest_nginx
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./storage:/app/storage:ro

    depends_on:
      backend:
        condition: service_healthy
