version: '3.8'

services:
  backend:
    build: ./backend
    container_name: filenest_backend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
      - ./data:/app/data
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:stable-alpine
    container_name: filenest_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./storage:/app/storage:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      backend:
        condition: service_healthy
